language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "3.6"
install:
  - pushd /tmp
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.12.3/protoc-3.12.3-linux-x86_64.zip
  - unzip protoc-3.12.3-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  - chmod +x ./compile_base.py
  - ./compile_base.py -l cpp -1 -k
  - clang-format-3.8 -i -style file $(find src -name "*.proto")
  - git diff --exit-code
