language: python
python:
  - "2.7"
install:
  - pushd /tmp
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
  - unzip protoc-3.1.0-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  - ./compile.py python
